### ISSUE TITLE
explorer.cardano.org is down

### ISSUE THREAD

**Issue by jtomtan** [input-output-hk/cardano-explorer-app#297]
Hi, guys,

https://explorer.cardano.org/ is currently down, would someone take a look at it and bring it back? Thanks.

And I am from Ownbit wallet team. The latest version of Ownbit is supporting ADA now. Can we share the news to the community together? And is there some 3rd party ADA Waller’s webpage, so that Ownbit can be added?

Website: https://ownbit.io 

Thanks for your help.

Best Regards from Ownbit team

**Comment by rhyslbw** [comment]
Thanks for the report @jtomtan

Our service team was already investigating and since resolved the issue. Please note, `cardano-explorer-app` and the new backend services are not being served at https://explorer.cardano.org/ yet, however this is due to change very soon.

> The latest version of Ownbit is supporting ADA now. Can we share the news to the community together?
Fantastic! I'll ask a team member from the relevant area to get in touch

**Comment by jtomtan** [comment]
> Thanks for the report @jtomtan
> 
> Our service team was already investigating and since resolved the issue. Please note, `cardano-explorer-app` and the new backend services are not being served at https://explorer.cardano.org/ yet, however this is due to change very soon.
> 
> > The latest version of Ownbit is supporting ADA now. Can we share the news to the community together?
> 
> Fantastic! I'll ask a team member from the relevant area to get in touch

Thanks for the reply. Please let me know if someone I can contact.
