### ISSUE TITLE
Explorer shows no data if latest epoch isn't populated

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-explorer-app#307]
The explorer doesn't show any data at all if the latest epoch isn't correct. It should be able to show the epoch data and most recent blocks it has even if it's not up to date.

**Comment by rhyslbw** [comment]
The problem here relates to the dataset being in an inconsistent state, and currently the API doesn't reject queries to avoid unexpected results. With this in mind, the change to the app should be limited to setting up response handling that just informs the user of the outage, rather than showing a loaders.
